stages:
  data_loader:
    cmd: python -m src.modules.data_loader
    deps:
      - src/modules/data_loader.py
    outs:
      - data_artifacts/raw_data.csv
      - data_artifacts/train_data.csv
      - data_artifacts/test_data.csv


  data_transformation:
    cmd: python -m src.modules.data_transformation
    deps:
      - src/modules/data_transformation.py
    outs:
      - data_artifacts/test_transformed_data.csv
      - data_artifacts/train_transformed_data.csv
      - model_artifacts/transformation.pkl

  model_training:
    cmd: python -m src.modules.model_training_reg
    deps:
      - src/modules/model_training_reg.py
    outs:
      - model_artifacts/model.pkl